/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TenPinBowling;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;


public class AppTest {
    private Game gm;
    
    public AppTest(){
        
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() throws Exception {
        gm = new Game();
    }
    
    @After
    public void tearDown() {
    }

   
     @Test
     public void testGutterGame() throws Exception {
         rollMany(20, 0);
         assertEquals(0, gm.score());

     }
     
     
     private void rollMany(int n, int pins){
         for (int i = 0; i < n; i++) {
             gm.roll(pins);
         }
     }
     
     @Test
     public void testAllOnes() throws Exception{
            rollMany(20, 1);
            assertEquals(20, gm.score());
    
         }
     
      @Test
      public void testOneSpare() throws Exception{
          rollSpare();
          gm.roll(3);
          rollMany(17,0);
          assertEquals(16, gm.score());
      }
      
      
      private void rollSpare(){
          gm.roll(5);
          gm.roll(5);
      }
      
      @Test
      public void testOneStrike() throws Exception{
          rollStrike();
          gm.roll(3);
          gm.roll(4);
          rollMany(16,0);
          assertEquals(24,gm.score());
          
      }
      
      private void rollStrike(){
          gm.roll(10);
      }
      
      @Test
      public void testPerfectGame() throws Exception{
          rollMany(12, 10);
          assertEquals(300, gm.score());
      }
}
